use_frameworks!

platform :ios, '8.0'

target 'CCAlertController_Example' do
  pod 'CCAlertController', :path => '../'

  target 'CCAlertController_Tests' do
    inherit! :search_paths

    
  end
end
